smucclaw/vue-pure-pdpa

package-lock.json, package.json, src/assets/main.scss, src/components/HelloWorld.vue, src/main.js, src/views/Home.vue
=> integrate bulma and added example button

package-lock.json, package.json, src/App.vue, src/store/index.js, src/views/Editor.vue, src/views/Home.vue, test/Main.purs
- added console to evaluate javascript and show output in the browser (not dev tools)
- used `vuex-map-fields` to automatically generate getters to store fields
- instead of mutating store directly, use mutation functions and call `store.commit('mutation', args...)`
=> added console output for editor

package-lock.json, package.json, src/App.vue, src/views/About.vue, src/views/Editor.vue, src/views/Home.vue
Close #9 
Let me know if this is ok @tws4793
=> integrate pugjs

.dockerignore, Dockerfile, docker-compose.yml
To simplify the process of setting up, running and tearing down the application, we propose taking advantage of Docker containers.
- `Dockerfile` to specify build and setup steps
- `.dockerignore` file to ignore certain directories when running the COPY instructions set by the `Dockerfile`
- `docker-compose.yml` to set the parameters for running the container
=> Create container for deployment

src/App.vue, src/components/QuestionBase.vue, src/components/QuestionRadio.vue, src/components/questions/Question.vue, src/store/index.js, src/views/Questions.vue
Redesign the Question component which is now `QuestionBase.vue`.
- Rename `src/components/questions/Question.vue` to `src/components/QuestionBase.vue`
- Redesign `QuestionBase.vue`
- Modify styling and move 'I Don't Know' button to end in `QuestionRadio.vue` component
- Add bottom spacing in container div in `App.vue`
- "Must Sing" example from store
=> UI redesign - Question component

bin/v8k, package-lock.json, package.json, packages.dhall
vue-big is a full copy of the vue-pure-pdpa repo
vue-small is a cut-down version with symlinked .git node_modules output
not sure what's going on with the purescript versions in packages.dhall
=> add convenience script to help manage the pool of vue dev servers

public/index.html, src/components/TheMain.vue, src/router/index.js
I've hard coded the change in the index.html file:
<title>Dolora the Law Explorer</title>
It was previously:
<title><%= htmlWebpackPlugin.options.title %></title>
Strangely, I could not find the specific name "Dolores" anywhere in https://github.com/smucclaw/vue-pure-pdpa when I did a search for the name.
=> changing 'Dolores' to 'Dolora the Law Explorer'

tests/purescript/AnyAll/Rendering.purs
commented out PdpaQ.purs test in Rendering.purs.
=> commented out PdpaQ.purs test in Rendering.purs

bin/v8k
- Add type hints
- replace % with f-strings
=> Modernize python

bin/v8k
STDOUT is expected to return with something like
```
:8098/50f66ea4-7d93-4172-8f00-3f2db5cd6a0d/1leBCZhgDsn-Abg2H_OINGGv-8Gpf9mzuX1RR56v0Sss/1411370405
```
=> 20230516 v8k fix

src/AnyAll.purs
Reverts smucclaw/vue-pure-pdpa#80 so that it compiles
=> Revert "added a few type signatures to clarify functions"

vue.config.js
undo rogue commit https://github.com/smucclaw/vue-pure-pdpa/commit/dfbe8ab64ae95d9f812a20472a0a8f5df051910c
=> remove devServer stanza again, that was a rogue commit

package-lock.json, package.json, src/components/LadderDiagram.vue
this uses the main ladder-diagram library on npm
-jules
=> Fix clickable ladder diagram

vue.config.js
i think we've run with this and this should go into main
=> Add config for proxied version

bin/https.md
=> Document https

src/AnyAll.purs, src/AnyAll/Relevance.purs, src/AnyAll/Types.purs, tests/purescript/AnyAll/PdpaQ.purs, tests/purescript/AnyAll/Rendering.purs, tests/purescript/AnyAll/ViewHide.purs, tests/unit/QuotJs.spec.ts
- **Partial**
- **Finish removing tagNL**
=> Remove unused tagNL

src/router/index.js
- **Add index route**
- **Change name**
=> index.html route

src/components/QuestionRadio.vue
- **Partial work**
- **Finalize setup script**
=> setup script QuestionRadio

src/components/TheQuestion.vue, src/components/__tests__/TheQuestion.spec.js
- **Partial work for script setup**
- **Finish converting TheQuestion to setup script**
=> script setup TheQuestion

src/components/QuestionBase.vue, src/model/MarkDetails.ts, src/model/Relevance.ts, src/model/__tests__/MarkDetails.test.ts, src/store/index.ts
- **Partial**
- **Partial**
- **Dirty but works**
- **Cleanup**
=> mark ternary
